# Generated by Django 6.0 on 2026-01-08 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 18, 5, 3, 924190)),
        ),
    ]
