# Generated by Django 6.0 on 2026-01-14 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usagesession_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usagesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 19, 2, 11, 569661)),
        ),
    ]
