# Generated by Django 5.2.10 on 2026-01-28 13:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_blocked_alter_usagesession_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 10, 56, 39, 14595)),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=datetime.datetime(2026, 1, 28, 10, 56, 39, 14876))),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
